site_name: 文档中心
theme:
   name: material   
   palette:
           - scheme: default
             toggle:
                     icon: material/toggle-switch-off-outline
                     name: Switch to dark mode
             primary: white
           - scheme: black
             toggle:
                     icon: material/toggle-switch
                     name: Switch to light mode
             primary: black 
   logo:
         https://www.rvboards.org/assets/img/logo_header.png 
   favicon: 
        ./RV.png
   features:
        - header.autohide
        - navigation.top

copyright: Copyright © PerfXLab 澎峰科技 All Rights Reserved
extra:
          homepage: https://www.rvboards.org
          alternate:
                  #Switch to English
                  - name: English
                    link: https://www.rvboards.org/mkdocs/en/
                    lang: en
                  - name: 简体中文
                    link: https://www.rvboards.org/mkdocs/zh/
                    lang: zh
extra_css:
        - stylesheets/extra.css
nav:
    - D1板卡:
            - D1芯片介绍: nezha-d1.md
            - D1-开发板--nezha: D1.md
            - 系统镜像制作及烧录指导:
                    - Tina Linux 系统介绍: Tina_linux系统.md 
                    - Debian系统烧录以及镜像软件源配置: Debian.md
                    - 源码下载: 源码下载.md
                    - 编译环境配置: 编译环境配置.md
                    - 开发板硬件简介: 开发板硬件简介.md
            - Demo实验及演示:
                    - 温湿度传感器DHT11: 温湿度传感器DHT11.md
                    - 实时时钟模块DS1302: 实时时钟模块DS1302.md
                    - 倾斜模块: 倾斜模块.md
                    - 循迹避障模块TCRT5000: 循迹避障模块TCRT5000.md
                    - 光照强度传感器: 光照强度传感器.md
                    - 颜色传感器TCS3200: 颜色传感器TCS3200.md
                    - 大气压强传感器BMP280: 大气压强传感器BMP280.md
                    - 三色led灯模块: 三色led灯模块.md
                    - 4*4矩阵键盘: 矩阵键盘.md
                    - Spi-Lcd 3.5屏幕(ic：ili9486l): Spi-Lcd3.5屏幕ic：ili9486l.md
                    - NES模拟器: NES模拟器.md
                    - 在HDMI显示器上运行QT示例: 在HDMI显示器上运行QT示例.md
            - 资源获取:
                    - 研发生产工具: 研发生产工具.md
                    - 固件下载: 固件下载.md
            - 常见问题:
                    - FAQ: FAQ.md
                      #    - Perf-v:
                      # - 样例:
                      # - Perf-v: perf-v.md
    - Perf-V板卡:
            - Perf-V介绍: Perf-V介绍.md
            - Perf-V原理: Perf-V原理.md
            - Perf-V的Demo演示:
                    - 蜂鸟软核环境配置:
                            - 蜂鸟简介: 蜂鸟简介.md
                            - RISC-V开发环境教程:
                                    - 需要安装的软件: 蜂鸟需要安装的软件.md
                                    - 使用教程:
                                            - 蜂鸟软核下载到Perf-V: 蜂鸟软核下载到Perf-V.md
                                            - 程序下载到蜂鸟软核: 程序下载到蜂鸟软核.md
                    - Demo制作过程: 
                            - FPGA_DEMO:
                                    - 流水灯: 流水灯.md
                                    - DDR3: DDR3.md
                                    - 摄像头 HDMI 显示(高速--HDMI&摄像头): HDMI&摄像头.md
                                    - 摄像头 HDMI 显示(高速--HDMI): 高速HDMI.md
                                    - 摄像头 VGA 显示(高速--VGA): 高速VGA.md
                                    - 简易电压表设计: 简易电压表设计.md
                                    - 千兆以太网: 千兆以太网.md
                                    - USB 传输: USB传输.md
                                    - 串口通信: 串口通信.md
                                    - 基于 Perf-V 波形发生器: 波形发生器.md
                                    - 贪吃蛇小游戏: 贪吃蛇小游戏.md
                                    - 温湿度传感器的应用: 温湿度传感器的应用.md
                                    - XADC: XADC.md
                                    - 芯片片内温度的采集: 芯片片内温度的采集.md
                            - 蜂鸟_DEMO:
                                    - 三色LED灯显示实验: 基于蜂鸟三色LED灯显示实验.md
                                    - LED点阵实验: 基于蜂鸟LED点阵实验.md
                                    - 智能小车: 基于蜂鸟的智能小车.md
                                    - TFT屏幕显示实验: 基于蜂鸟TFT屏幕显示实验.md
                                    - 基于 RISCV 简易示波器实验: 简易示波器实验.md
                                    - 基于 RISCV 四轴飞行器实验: 四轴飞行器实验.md
            - Perf-V IDE介绍及使用: IDE介绍及使用.md        
            - 资源获取: 资源获取.md 
            - 常见问题汇总: 常见问题.md
    
    
