site_name: 文档中心
theme:
   name: material   
   palette:
           - scheme: default
             toggle:
                     icon: material/toggle-switch-off-outline
                     name: Switch to dark mode
             primary: white
           - scheme: black
             toggle:
                     icon: material/toggle-switch
                     name: Switch to light mode
             primary: black 
   logo:
         https://www.rvboards.org/assets/img/logo_header.png 
   favicon: 
        ./RV.png
   features:
        - header.autohide
        - navigation.top

copyright: Copyright © PerfXLab 澎峰科技 All Rights Reserved
extra:
          homepage: https://www.rvboards.org
          alternate:
                  #Switch to English
                  - name: English
                    link: https://www.rvboards.org/mkdocs/en/
                    lang: en
                  - name: 简体中文
                    link: https://www.rvboards.org/mkdocs/zh/
                    lang: zh
extra_css:
        - stylesheets/extra.css
nav:
    - D1板卡:
            - D1芯片介绍: nezha-d1.md
            - D1-开发板--nezha: D1.md
            - 系统镜像制作及烧录指导:
                    - Tina Linux 系统介绍: Tina_linux系统.md 
                    - 源码下载: 源码下载.md
                    - 编译环境配置: 编译环境配置.md
                    - 编译和烧写: 编译和烧写.md
                    - 开发板硬件简介: 开发板硬件简介.md
            - Demo实验及演示:
                    - 温湿度传感器DHT11: 温湿度传感器DHT11.md
                    - 实时时钟模块DS1302: 实时时钟模块DS1302.md
                    - 倾斜模块: 倾斜模块.md
                    - 循迹避障模块TCRT5000: 循迹避障模块TCRT5000.md
                    - 光照强度传感器: 光照强度传感器.md
                    - 颜色传感器TCS3200: 颜色传感器TCS3200.md
                    - 大气压强传感器BMP280: 大气压强传感器BMP280.md
                    - 三色led灯模块: 三色led灯模块.md
                    - 4*4矩阵键盘: 矩阵键盘.md
                    - Spi-Lcd 3.5屏幕(ic：ili9486l): Spi-Lcd3.5屏幕ic：ili9486l.md
            - 资源获取:
                    - 资源汇总: 资源汇总.md
                    - 研发生产工具: 研发生产工具.md
                    - 固件下载: 固件下载.md
            - 常见问题:
                    - FAQ: FAQ.md
                      #    - Perf-v:
                      # - 样例:
                      # - Perf-v: perf-v.md
