site_name: Document Center
theme:
   name: material   
   palette:
           - scheme: default
             toggle:
                     icon: material/toggle-switch-off-outline
                     name: Switch to dark mode
             primary: white
           - scheme: black
             toggle:
                     icon: material/toggle-switch
                     name: Switch to light mode
             primary: black 
   logo:
         https://www.rvboards.org/assets/img/logo_header.png 
   favicon: 
        ./RV.png
   features:
        - header.autohide
        - navigation.top
        
copyright: Copyright © PerfXLab 澎峰科技 All Rights Reserved
extra:
          homepage: https://www.rvboards.org
          alternate:
                  #Switch to English
                  - name: English
                    link: https://www.rvboards.org/mkdocs/en/
                    lang: en
                  - name: 简体中文
                    link: https://www.rvboards.org/mkdocs/zh/
                    lang: zh
extra_css:
        - stylesheets/extra.css
nav:
    - D1-Board:
            - D1-Boards Introduction: nezha-d1.md 
            - D1-Development board--nezha: D1.md
            - System image making and burning instruction:
                    - Tina Linux System Introduction: Tina_linux系统.md 
                    - Debian system burning and mirroring software source configuration: Debian.md
                    - Source code download: 源码下载.md
                    - Compile environment configuration: 编译环境配置.md
                    - Brief introduction of development board hardware: 开发板硬件简介.md
            - Demo experiment and demonstration:
                    - Temperature and humidity sensor DHT11: 温湿度传感器DHT11.md
                    - Real time clock module DS1302: 实时时钟模块DS1302.md
                    - Tilt module: 倾斜模块.md
                    - Tracking and obstacle avoidance module TCRT5000: 循迹避障模块TCRT5000.md
                    - Light intensity sensor: 光照强度传感器.md
                    - Color sensor TCS3200: 颜色传感器TCS3200.md
                    - Atmospheric pressure sensor BMP280: 大气压强传感器BMP280.md
                    - Three color LED lamp module: 三色led灯模块.md
                    - 4X4 matrix keyboard: 矩阵键盘.md
                    - Spi-Lcd 3.5 Screen: Spi-Lcd35屏幕ili9486l.md
                    - Running the QT example: Running the QT example.md
            - Resource acquisition:
                    - Resource summary: RS.md
                    - R&D production tools: 研发生产工具.md
                    - Firmware Download: 固件下载.md
            - Normal question:
                    - FAQ: FAQ.md
    - Perf-V Board:
            - Perf-V Introduction: Perf-V介绍.md
            - Principle of Perf-V: Perf-V原理.md
            - Demo of Perf-V:
                    - Hummingbird Softcore Environment Configuration:
                            - Introduction to Hummingbird: 蜂鸟简介.md
                            - RISC-V development environment tutorial:
                                    - Software to be installed: 蜂鸟需要安装的软件.md
                                    - Tutorials:
                                            - Downloading Hummingbird Softcore to Perf-V: 蜂鸟软核下载到Perf-V.md
                                            - Program download to Hummingbird Softcore: 程序下载到蜂鸟软核.md
                    - Demo creation process: 
                            - FPGA_DEMO:
                                    - Streaming Lights: 流水灯.md
                                    - DDR3: DDR3.md
                                    - Camera HDMI Display(High Speed - HDMI & Camera): HDMI&摄像头.md
                                    - Camera HDMI Display(High Speed - HDMI): 高速HDMI.md
                                    - Camera VGA Display(High Speed - VGA): 高速VGA.md
                                    - Simple voltmeter design: 简易电压表设计.md
                                    - Gigabit Ethernet: 千兆以太网.md
                                    - USB Transmission: USB传输.md
                                    - Serial communication: 串口通信.md
                                    - Perf-V based waveform generator: 波形发生器.md
                                    - Gluttony mini-game: 贪吃蛇小游戏.md
                                    - Application of temperature and humidity sensor: 温湿度传感器的应用.md
                                    - XADC: XADC.md
                                    - On-chip temperature acquisition: 芯片片内温度的采集.md
                            - Hummingbird_DEMO:
                                    - Tri-color LED light display experiment: 基于蜂鸟三色LED灯显示实验.md
                                    - LED dot matrix experiment: 基于蜂鸟LED点阵实验.md
                                    - Smart Car: 基于蜂鸟的智能小车.md
                                    - TFT screen display experiment: 基于蜂鸟TFT屏幕显示实验.md
                                    - RISCV based simple oscilloscope experiment: 简易示波器实验.md
                                    - RISCV based quadcopter experiment: 四轴飞行器实验.md
            - Perf-V IDE Introduction and Usage: IDE介绍及使用.md        
            - Resources: 资源获取.md 
            - FAQ: FAQ-PerfV.md
